#!/bin/bash

echo "### Creating VMs ###"
ansible-playbook create_instances.yaml -e role=master -e count=1 &
ansible-playbook create_instances.yaml -e role=node -e count=3 &
ansible-playbook create_instances.yaml -e role=nfs -e count=1 &
wait
echo "### VMs created ###"

echo

echo "### VMs created ###"
ansible-playbook -b simple-cluster.yaml
ansible-playbook -b add-dashboard-to-cluster.yaml
ansible-playbook -b heapster-with-influxdb.yaml

