#
# Testing Ansible hostvars
#
---
- hosts: tag_role_master
  tasks:
    - name: Generate cluster token
      shell: /bin/kubeadm token generate
      register: kubeadm_token_generate

    - name: set token variable
      set_fact:
        kubeadm_token: "{{ kubeadm_token_generate.stdout }}"

- hosts: tag_role_node
  tasks:
    - name: Determine master node
      set_fact:
        master: "{{ groups['tag_role_master'][0] }}"
    #- debug: msg="{{ master }}"
    - set_fact: token="{{ hostvars[master]['kubeadm_token'] }}"
    - debug: var=token

        

