---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair:	     thomas_internet_home
    instance_type:   t2.medium
    #security_group: thomas_internet_ssh
    security_group:  thomas_internet_all_open
    #image:	     ami-5652ce39	# Amazon Linux
    image:	     ami-194cdc76	# RHEL 7.4
    region:	     eu-central-1
    subnet:	     subnet-a2a831d8
    count:           3
    owner:           thomas
    role:            node
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ subnet }}"
         assign_public_ip: yes
         instance_tags:
           owner: "{{ owner }}"
           role:  "{{ role }}"
         count: "{{ count }}"
      register: ec2

    - debug:  var=ec2.instances.public_ip

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

#- name: Configure instance(s)
#  hosts: launched
#  become: True
#  gather_facts: True
#  roles:
#    - my_awesome_role
#    - my_awesome_test
#
#- name: Terminate instances
#  hosts: localhost
#  connection: local
#  tasks:
#    - name: Terminate instances that were previously launched
#      ec2:
#        state: 'absent'
#        instance_ids: '{{ ec2.instance_ids }}'

