#
# Add dependencies for Ingress
# https://kubernetes.io/docs/concepts/services-networking/ingress/
#
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: get info on master node
      ec2_instance_facts:
        filters:
          instance-state-name: running
          "tag:owner": thomas
          "tag:role": master
      register: ec2

    - set_fact: master_public_dns="{{ ec2['instances'][0]['public_dns_name'] }}"

- hosts: tag_role_master
  gather_facts: no
  tasks:
    - name: copy Ingress yaml config files to master node
      copy:
        src:  ingress-files/
        dest: /root/ingress-files

    - name: create Kubernetes Ingress objects
      shell: "kubectl apply -f /root/ingress-files/{{ item }}"
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      with_items:
        - 10_namespace.yaml              # Add 'ingress-nginx' namespace.
        - 20_default-backend.yaml        # Add 'default-http-backend' deployment.
                                         # This is an nginx webserver to serve all requests
                                         # not known to the Ingress Controller. These will
                                         # get a 404 HTTP response.
                                         # Also add a 'default-http-backend' service.
        - 30_configmap.yaml              # Add 'nginx-configuration' configmap.
        - 40_tcp-services-configmap.yaml # Add 'tcp-services' configmap.
        - 50_udp-services-configmap.yaml # Add 'udp-services' configmap.
        - 60_rbac.yaml                   # prepare rbac role and binding
        - 70_with-rbac.yaml              # install 'ingress-nginx' deployment
        - 80_service-nodeport.yaml       # add service for the deployment
        - 90_configmap.yaml              # create configmap, use for custom settings

    - set_fact: master_public_dns="{{ hostvars['localhost']['master_public_dns'] }}"

    - name: copy dashboard input file
      template:
        src: templates/dashboard-ingress.template
        dest: /root/dashboard-ingress.template

    - name: create Ingress for dashboard
      shell: "kubectl apply -f /root/dashboard-ingress.template"
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

