#
# Create a simple Kubernetes cluster:
#   - 1x Master (+ etcd)
#   - 2x Worker nodes
#
---
- hosts: kube-master:kube-node
  tasks:
    - name: setup Kubernetes RPM repository
      copy:
        src: files/k8s.repo
        dest: /etc/yum.repos.d/kubernetes.repo

    - shell: yum-config-manager --enable rhui-REGION-rhel-server-extras

    - selinux: state=disabled

    - name: install Docker
      yum:
        name: docker
        state: installed

    - name: install K8S packages
      yum:
        name: "{{  item }}"
        state: installed
      with_items:
        - kubelet
        - kubeadm
        - kubectl

    - name: customise kubelet service
      copy:
        src: files/10-kubeadm.conf
        dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

    - name: enable Docker and Kubelet service
      service:
        name: "{{ item }}"
        state: started       
        enabled: yes
      with_items:
        - docker
        - kubelet

    - name: enable IPv4 forwarding
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
        reload: yes

    - name: prepare for Calico networking
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /etc/cni
        - /etc/cni/net.d

- hosts: kube-master
  vars:
    k8s_version_string: v1.9.2

  tasks:
    - name: copy config files to master
      copy:
        src: "files/{{ item }}"
        dest: "/root/{{ item }}"
      with_items:
        - calico-3.0.yaml

    - name: prepare kubeadm.config on master
      template:
        src: templates/kubeadm.config.template
        dest: /root/kubeadm.config

#    - name: create cluster
#      shell: kubeadm init --config /root/kubeadm.config


