#
# Create a simple Kubernetes cluster:
#   - 1x Master (+ etcd)
#   - 2x Worker nodes
#
---
- hosts: tag_role_master:tag_role_node
  tags:
    - prepare_all
  vars:
    - version: 1.13.4
  vars_files:
    - vars/kubernetes-{{version}}.yaml
  tasks:
    - name: setup Kubernetes RPM repository
      copy:
        src: files/k8s.repo
        dest: /etc/yum.repos.d/kubernetes.repo

    - selinux: state=disabled

    - name: install K8S packages
      yum:
        name: "{{  rpm_list }}"
        state: installed

    - name: enable Docker and Kubelet service
      service:
        name: "{{ item }}"
        state: started       
        enabled: yes
      with_items:
        - docker
        - kubelet

    - name: enable IPv4 forwarding
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
        reload: yes

    - name: prepare for Calico networking
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /etc/cni
        - /etc/cni/net.d

- hosts: tag_role_master
  tasks:
    - name: Generate cluster token
      shell: /bin/kubeadm token generate
      register: kubeadm_token_generate

    - set_fact: kubeadm_token={{ kubeadm_token_generate.stdout }}
    - set_fact: master={{ inventory_hostname }}

    - name: prepare kubeadm.config and calico.yaml on master
      template:
        src: "templates/{{ item }}"
        dest: "/root/{{ item }}"
      with_items:
        - kubeadm_init_{{ version }}.template
        - calico-2.6.8.yaml

    - name: create cluster
      shell: kubeadm init --config /root/kubeadm.config

    - name: Create cluster network
      command: kubectl create -f /root/calico-2.6.8.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

- hosts: tag_role_node
  tasks:
    - set_fact: master="{{ groups['tag_role_master'][0] }}"
    - set_fact: kubeadm_token="{{ hostvars[ master]['kubeadm_token'] }}"
    - set_fact: cluster_name="{{ hostvars[master]['ansible_host'] }}"

    - name: Join cluster
      shell: "kubeadm join --token {{ kubeadm_token }} --discovery-token-unsafe-skip-ca-verification {{ cluster_name }}:6443"

