#
# Testing Ansible hostvars
#
---
- hosts: tag_role_master
  tasks:
    - name: Generate cluster token
      shell: /bin/kubeadm token generate
      register: kubeadm_token_generate

    - set_fact: kubeadm_token={{ kubeadm_token_generate.stdout }}

- hosts: tag_role_node
  tasks:
    - debug: var=groups["tag_role_master"][0]
